"""Argument-parser assembly for the Auto Dev control-plane front door."""

from __future__ import annotations

import argparse
import os
from typing import Any


def add_repo_root(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--repo-root", default=".")


def build_parser(control) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, prog=os.environ.get("AUTO_DEV_CLI_PROG"))
    commands = parser.add_subparsers(dest="command", required=True)
    project = commands.add_parser("project")
    project_commands = project.add_subparsers(dest="project_command", required=True)
    project_inspect = project_commands.add_parser("inspect")
    project_inspect.add_argument("--repo-root", default=".")
    project_inspect.set_defaults(handler=control.command_project_inspect)
    project_init = project_commands.add_parser("init")
    project_init.add_argument("--repo-root", default=".")
    project_init.add_argument("--mode", choices=tuple(sorted(control.WORKSPACE_STORAGE_MODES)))
    project_init.add_argument("--git", action="store_true")
    project_init.add_argument("--initial-branch", default="main")
    project_init.add_argument("--confirmation-source", required=True)
    project_init.set_defaults(handler=control.command_project_init)
    project_migrate = project_commands.add_parser("migrate")
    project_migrate.add_argument("--repo-root", default=".")
    project_migrate.add_argument("--project-revision", type=int, required=True)
    project_migrate.add_argument("--confirmation-source", required=True)
    project_migrate.set_defaults(handler=control.command_project_migrate)
    project_context = commands.add_parser("project-context")
    project_context_commands = project_context.add_subparsers(
        dest="project_context_command", required=True
    )
    project_context_list = project_context_commands.add_parser("list")
    add_repo_root(project_context_list)
    project_context_list.set_defaults(handler=control.command_project_context_list)
    project_context_show = project_context_commands.add_parser("show")
    add_repo_root(project_context_show)
    project_context_show.add_argument("--context-id")
    project_context_show.set_defaults(handler=control.command_project_context_show)
    project_context_adopt = project_context_commands.add_parser("adopt")
    add_repo_root(project_context_adopt)
    project_context_adopt.add_argument("--project-revision", type=int, required=True)
    project_context_adopt.add_argument("--context-id", required=True)
    project_context_adopt.add_argument("--title", required=True)
    project_context_adopt.add_argument(
        "--lifecycle",
        choices=tuple(sorted(control.PROJECT_CONTEXT_LIFECYCLES)),
        default="provisional",
    )
    project_context_adopt.add_argument(
        "--coverage", choices=tuple(sorted(control.PROJECT_CONTEXT_COVERAGE)), default="partial"
    )
    project_context_adopt.add_argument("--authority-boundary", required=True)
    project_context_adopt.add_argument("--delivery-boundary", required=True)
    project_context_adopt.add_argument("--context-boundary", required=True)
    project_context_adopt.add_argument("--mission")
    project_context_adopt.add_argument("--external-ref-json", action="append", default=[])
    project_context_adopt.add_argument("--evidence-source", action="append", default=[])
    project_context_adopt.add_argument("--select", action="store_true")
    project_context_adopt.set_defaults(handler=control.command_project_context_adopt)
    project_context_set = project_context_commands.add_parser("set")
    add_repo_root(project_context_set)
    project_context_set.add_argument("--project-revision", type=int, required=True)
    project_context_set.add_argument("--context-id", required=True)
    project_context_set.add_argument("--title")
    project_context_set.add_argument(
        "--lifecycle", choices=tuple(sorted(control.PROJECT_CONTEXT_LIFECYCLES))
    )
    project_context_set.add_argument(
        "--coverage", choices=tuple(sorted(control.PROJECT_CONTEXT_COVERAGE))
    )
    project_context_set.add_argument("--authority-boundary")
    project_context_set.add_argument("--delivery-boundary")
    project_context_set.add_argument("--context-boundary")
    project_context_set.add_argument("--mission")
    project_context_set.add_argument("--external-ref-json", action="append", default=[])
    project_context_set.add_argument("--evidence-source", action="append", default=[])
    project_context_set.set_defaults(handler=control.command_project_context_set)
    project_context_select = project_context_commands.add_parser("select")
    add_repo_root(project_context_select)
    project_context_select.add_argument("--project-revision", type=int, required=True)
    project_context_select.add_argument("--context-id", required=True)
    project_context_select.set_defaults(handler=control.command_project_context_select)
    outcome = commands.add_parser("outcome")
    outcome_commands = outcome.add_subparsers(dest="outcome_command", required=True)
    outcome_list = outcome_commands.add_parser("list")
    add_repo_root(outcome_list)
    outcome_list.add_argument("--project-context")
    outcome_list.set_defaults(handler=control.command_outcome_list)
    outcome_show = outcome_commands.add_parser("show")
    add_repo_root(outcome_show)
    outcome_show.add_argument("--project-context")
    outcome_show.add_argument("--outcome-id", required=True)
    outcome_show.set_defaults(handler=control.command_outcome_show)
    outcome_add = outcome_commands.add_parser("add")
    add_repo_root(outcome_add)
    outcome_add.add_argument("--project-revision", type=int, required=True)
    outcome_add.add_argument("--project-context")
    outcome_add.add_argument("--outcome-id", required=True)
    outcome_add.add_argument("--title", required=True)
    outcome_add.add_argument("--statement", required=True)
    outcome_add.add_argument(
        "--status", choices=tuple(sorted(control.OUTCOME_STATUSES)), default="proposed"
    )
    outcome_add.add_argument("--acceptance", action="append", default=[])
    outcome_add.add_argument("--parent-id")
    outcome_add.add_argument("--intake-id")
    outcome_add.add_argument("--contract-json")
    outcome_add.set_defaults(handler=control.command_outcome_add)
    outcome_set = outcome_commands.add_parser("set")
    add_repo_root(outcome_set)
    outcome_set.add_argument("--project-revision", type=int, required=True)
    outcome_set.add_argument("--project-context")
    outcome_set.add_argument("--outcome-id", required=True)
    outcome_set.add_argument("--outcome-revision", type=int, required=True)
    outcome_set.add_argument("--title")
    outcome_set.add_argument("--statement")
    outcome_set.add_argument("--status", choices=tuple(sorted(control.OUTCOME_STATUSES)))
    outcome_set.add_argument("--acceptance", action="append", default=[])
    outcome_set.add_argument("--intake-id")
    outcome_set.add_argument("--contract-json")
    outcome_set.add_argument("--requirement-diff-confirmation")
    outcome_set.set_defaults(handler=control.command_outcome_set)
    outcome_link = outcome_commands.add_parser("link")
    add_repo_root(outcome_link)
    outcome_link.add_argument("--project-revision", type=int, required=True)
    outcome_link.add_argument("--project-context")
    outcome_link.add_argument("--source-id", required=True)
    outcome_link.add_argument("--target-id", required=True)
    outcome_link.add_argument(
        "--relation", choices=tuple(sorted(control.OUTCOME_RELATIONS)), required=True
    )
    outcome_link.add_argument("--outcome-revision", type=int, required=True)
    outcome_link.set_defaults(handler=control.command_outcome_link)
    outcome_move = outcome_commands.add_parser("move")
    add_repo_root(outcome_move)
    outcome_move.add_argument("--project-revision", type=int, required=True)
    outcome_move.add_argument("--project-context")
    outcome_move.add_argument("--outcome-id", required=True)
    outcome_move.add_argument("--parent-id")
    outcome_move.add_argument("--outcome-revision", type=int, required=True)
    outcome_move.add_argument("--requirement-diff-confirmation")
    outcome_move.set_defaults(handler=control.command_outcome_move)
    capability = commands.add_parser("capability")
    capability_commands = capability.add_subparsers(dest="capability_command", required=True)
    capability_list = capability_commands.add_parser("list")
    add_repo_root(capability_list)
    capability_list.add_argument("--project-context")
    capability_list.set_defaults(handler=control.command_capability_list)
    capability_add = capability_commands.add_parser("add")
    add_repo_root(capability_add)
    capability_add.add_argument("--project-revision", type=int, required=True)
    capability_add.add_argument("--project-context")
    capability_add.add_argument("--capability-id", required=True)
    capability_add.add_argument("--title", required=True)
    capability_add.add_argument("--statement", required=True)
    capability_add.add_argument(
        "--status", choices=tuple(sorted(control.CAPABILITY_STATUSES)), default="emerging"
    )
    capability_add.add_argument("--outcome-id", action="append", default=[])
    capability_add.add_argument("--evidence", action="append", default=[])
    capability_add.set_defaults(handler=control.command_capability_add)
    capability_set = capability_commands.add_parser("set")
    add_repo_root(capability_set)
    capability_set.add_argument("--project-revision", type=int, required=True)
    capability_set.add_argument("--project-context")
    capability_set.add_argument("--capability-id", required=True)
    capability_set.add_argument("--capability-revision", type=int, required=True)
    capability_set.add_argument("--title")
    capability_set.add_argument("--statement")
    capability_set.add_argument("--status", choices=tuple(sorted(control.CAPABILITY_STATUSES)))
    capability_set.add_argument("--outcome-id", action="append", default=[])
    capability_set.add_argument("--evidence", action="append", default=[])
    capability_set.set_defaults(handler=control.command_capability_set)
    activity = commands.add_parser("activity")
    activity_commands = activity.add_subparsers(dest="activity_command", required=True)
    activity_list = activity_commands.add_parser("list")
    add_repo_root(activity_list)
    activity_list.add_argument("--project-context")
    activity_list.set_defaults(handler=control.command_activity_list)
    activity_record = activity_commands.add_parser("record")
    add_repo_root(activity_record)
    activity_record.add_argument("--project-revision", type=int, required=True)
    activity_record.add_argument("--activity-id")
    activity_record.add_argument("--project-context")
    activity_record.add_argument("--outcome-id")
    activity_record.add_argument("--intake-id", required=True)
    activity_record.add_argument("--summary", required=True)
    activity_record.add_argument(
        "--result", choices=("passed", "failed", "partial"), default="passed"
    )
    activity_record.add_argument("--path", action="append", default=[])
    activity_record.add_argument("--validation", action="append", default=[])
    activity_record.set_defaults(handler=control.command_activity_record)
    focus = commands.add_parser("focus")
    focus_commands = focus.add_subparsers(dest="focus_command", required=True)
    focus_show = focus_commands.add_parser("show")
    add_repo_root(focus_show)
    focus_show.add_argument("--session-key", required=True)
    focus_show.set_defaults(handler=control.command_focus_show)
    focus_set = focus_commands.add_parser("set")
    add_repo_root(focus_set)
    focus_set.add_argument("--session-key", required=True)
    focus_set.add_argument("--project-context")
    focus_set.add_argument("--kind", choices=("project", "outcome", "task", "plan"), required=True)
    focus_set.add_argument("--focus-id", required=True)
    focus_set.add_argument("--task-id")
    focus_set.set_defaults(handler=control.command_focus_set)
    intake = commands.add_parser("intake")
    intake_commands = intake.add_subparsers(dest="intake_command", required=True)
    intake_turn = intake_commands.add_parser("turn")
    add_repo_root(intake_turn)
    intake_turn.add_argument("--session-key", required=True)
    intake_turn.add_argument("--turn-id", required=True)
    intake_turn.add_argument("--task-id")
    intake_turn.set_defaults(handler=control.command_intake_turn)
    intake_status = intake_commands.add_parser("status")
    add_repo_root(intake_status)
    intake_status.add_argument("--session-key", required=True)
    intake_status.set_defaults(handler=control.command_intake_status)
    intake_assess = intake_commands.add_parser("assess")
    add_repo_root(intake_assess)
    intake_assess.add_argument("--session-key", required=True)
    intake_assess.add_argument("--turn-id", required=True)
    intake_assess.add_argument("--intake-id")
    intake_assess.add_argument("--depth", choices=tuple(sorted(control.INTAKE_DEPTHS)))
    intake_assess.add_argument("--summary")
    intake_assess.add_argument("--goal")
    intake_assess.add_argument("--inference")
    intake_assess.add_argument("--project-context")
    intake_assess.add_argument("--outcome-id")
    intake_assess.add_argument("--task-id")
    intake_assess.add_argument("--scope", action="append", default=[])
    intake_assess.add_argument("--acceptance", action="append", default=[])
    intake_assess.add_argument("--non-goal", action="append", default=[])
    intake_assess.add_argument("--assumption", action="append", default=[])
    intake_assess.add_argument("--fact", action="append", default=[])
    intake_assess.add_argument("--expert-completion", action="append", default=[])
    intake_assess.add_argument("--decision-json", action="append", default=[])
    intake_assess.add_argument("--assessment-json")
    intake_assess.add_argument("--contract-json")
    intake_assess.set_defaults(handler=control.command_intake_assess)
    intake_resolve = intake_commands.add_parser("resolve")
    add_repo_root(intake_resolve)
    intake_resolve.add_argument("--session-key", required=True)
    intake_resolve.add_argument("--turn-id", required=True)
    intake_resolve.add_argument("--intake-id", required=True)
    intake_resolve.add_argument("--intake-revision", type=int, required=True)
    intake_resolve.add_argument("--decision-id", required=True)
    intake_resolve.add_argument(
        "--status", choices=("accepted", "deferred", "excluded"), required=True
    )
    intake_resolve.add_argument("--resolution", required=True)
    intake_resolve.add_argument("--source", required=True)
    intake_resolve.set_defaults(handler=control.command_intake_resolve)
    intake_confirm = intake_commands.add_parser("confirm")
    add_repo_root(intake_confirm)
    intake_confirm.add_argument("--session-key", required=True)
    intake_confirm.add_argument("--turn-id", required=True)
    intake_confirm.add_argument("--intake-id", required=True)
    intake_confirm.add_argument("--intake-revision", type=int, required=True)
    intake_confirm.add_argument("--confirmation-source", required=True)
    intake_confirm.set_defaults(handler=control.command_intake_confirm)
    intake_reopen = intake_commands.add_parser("reopen")
    add_repo_root(intake_reopen)
    intake_reopen.add_argument("--session-key", required=True)
    intake_reopen.add_argument("--turn-id", required=True)
    intake_reopen.add_argument("--intake-id", required=True)
    intake_reopen.add_argument("--intake-revision", type=int, required=True)
    intake_reopen.add_argument("--reason", required=True)
    intake_reopen.set_defaults(handler=control.command_intake_reopen)
    intake_show = intake_commands.add_parser("show")
    add_repo_root(intake_show)
    intake_show.add_argument("--intake-id", required=True)
    intake_show.set_defaults(handler=control.command_intake_show)
    task = commands.add_parser("task")
    task_commands = task.add_subparsers(dest="task_command", required=True)
    task_list = task_commands.add_parser("list")
    task_list.add_argument("--repo-root", default=".")
    task_list.add_argument("--all", action="store_true")
    task_list.set_defaults(handler=control.command_task_list)
    task_select = task_commands.add_parser("select")
    task_select.add_argument("--repo-root", default=".")
    task_select.add_argument("--task-id", required=True)
    task_select.add_argument("--project-revision", type=int, required=True)
    task_select.add_argument("--confirmation-source", required=True)
    task_select.set_defaults(handler=control.command_task_select)
    task_pause = task_commands.add_parser("pause")
    task_pause.add_argument("--repo-root", default=".")
    task_pause.add_argument("--task-id")
    task_pause.add_argument("--state-revision", type=int, required=True)
    task_pause.add_argument("--reason", required=True)
    task_pause.set_defaults(handler=control.command_task_pause)
    task_amend_scope = task_commands.add_parser("amend-scope")
    task_amend_scope.add_argument("--repo-root", default=".")
    task_amend_scope.add_argument("--state-revision", type=int, required=True)
    task_amend_scope.add_argument("--scope", action="append", required=True)
    task_amend_scope.add_argument("--kind", choices=("adjacent", "requirement-diff"), required=True)
    task_amend_scope.add_argument("--reason", required=True)
    task_amend_scope.add_argument("--confirmation-source")
    task_amend_scope.set_defaults(handler=control.command_task_amend_scope)
    task_review = task_commands.add_parser("review")
    task_review.add_argument("--repo-root", default=".")
    task_review.add_argument("--state-revision", type=int, required=True)
    task_review.add_argument("--summary", required=True)
    task_review.add_argument("--file", action="append", default=[])
    task_review.add_argument("--validation", action="append", required=True)
    task_review.add_argument("--risk", action="append", default=[])
    product_review_input = task_review.add_mutually_exclusive_group()
    product_review_input.add_argument("--product-review-file")
    product_review_input.add_argument("--product-review-json")
    task_review.set_defaults(handler=control.command_task_review)
    task_resume = task_commands.add_parser("resume")
    task_resume.add_argument("--repo-root", default=".")
    task_resume.add_argument("--state-revision", type=int, required=True)
    task_resume.add_argument("--reason", required=True)
    task_resume.add_argument("--confirmation-source", required=True)
    task_resume.set_defaults(handler=control.command_task_resume)
    task_attribute = task_commands.add_parser("attribute")
    add_repo_root(task_attribute)
    task_attribute.add_argument("--state-revision", type=int, required=True)
    task_attribute.add_argument("--project-context")
    task_attribute.add_argument("--outcome-id")
    task_attribute.add_argument("--intake-id")
    task_attribute.add_argument("--source", required=True)
    task_attribute.set_defaults(handler=control.command_task_attribute)
    fix = commands.add_parser("fix")
    fix_commands = fix.add_subparsers(dest="fix_command", required=True)
    fix_inspect = fix_commands.add_parser("inspect")
    add_repo_root(fix_inspect)
    fix_inspect.set_defaults(handler=control.command_fix_inspect)
    fix_apply = fix_commands.add_parser("apply")
    add_repo_root(fix_apply)
    fix_apply.add_argument(
        "--operation",
        choices=(
            "restore-task",
            "reconcile-projection",
            "recover-interrupted-upgrade",
        ),
        required=True,
    )
    fix_apply.add_argument("--task-id")
    fix_apply.add_argument("--expected-task-revision", type=int)
    fix_apply.add_argument("--expected-project-revision", type=int)
    fix_apply.add_argument("--upgrade-id")
    fix_apply.add_argument("--expected-upgrade-manifest-sha256")
    fix_apply.add_argument("--expected-current-fingerprint")
    fix_apply.add_argument("--target-status", choices=("active", "review_ready"))
    fix_apply.add_argument("--replace-selected-task-id")
    fix_apply.add_argument("--expected-selected-task-revision", type=int)
    fix_apply.add_argument("--reason", required=True)
    fix_apply.add_argument("--confirmation-source", required=True)
    fix_apply.set_defaults(handler=control.command_fix_apply)
    legacy_upgrade = commands.add_parser("legacy-upgrade")
    legacy_upgrade_commands = legacy_upgrade.add_subparsers(
        dest="legacy_upgrade_command", required=True
    )
    legacy_upgrade_inspect = legacy_upgrade_commands.add_parser("inspect")
    add_repo_root(legacy_upgrade_inspect)
    legacy_upgrade_inspect.set_defaults(handler=control.command_legacy_upgrade_inspect)
    legacy_upgrade_apply = legacy_upgrade_commands.add_parser("apply")
    add_repo_root(legacy_upgrade_apply)
    legacy_upgrade_apply.add_argument("--project-revision", type=int, required=True)
    legacy_upgrade_apply.add_argument("--active-task-revision", type=int)
    legacy_upgrade_apply.add_argument("--expected-upgrade-version", type=int, required=True)
    legacy_upgrade_apply.add_argument("--expected-step", action="append", required=True)
    legacy_upgrade_apply.add_argument("--expected-fingerprint", required=True)
    legacy_upgrade_apply.add_argument("--reason", required=True)
    legacy_upgrade_apply.add_argument("--confirmation-source", required=True)
    legacy_upgrade_apply.set_defaults(handler=control.command_legacy_upgrade_apply)
    snapshot = commands.add_parser("snapshot")
    snapshot_commands = snapshot.add_subparsers(dest="snapshot_command", required=True)
    snapshot_prune = snapshot_commands.add_parser(
        "prune", help="read-only snapshot reference and reclaim-space dry run"
    )
    add_repo_root(snapshot_prune)
    snapshot_prune.set_defaults(handler=control.command_snapshot_prune)
    start = commands.add_parser("start")
    add_repo_root(start)
    start.add_argument("--tier", choices=("direct", "team"), required=True)
    start.add_argument("--task", required=True)
    start.add_argument("--requirement-receipt", required=True)
    start.add_argument("--confirmation-source", required=True)
    start.add_argument("--project-context")
    start.add_argument("--outcome-id")
    start.add_argument("--intake-id")
    start.add_argument("--acceptance", action="append", required=True)
    start.add_argument("--evidence", action="append", default=[])
    start.add_argument("--scope", action="append", default=[])
    start.add_argument(
        "--snapshot-mode",
        choices=("auto", "none", "manifest", "full"),
        default="auto",
        help="snapshot policy; Git defaults to a stat manifest, full copies are opt-in",
    )
    start.add_argument(
        "--snapshot-scope",
        action="append",
        default=[],
        help="narrow the files preserved in the snapshot without changing the write gate",
    )
    start.add_argument("--validation", action="append", default=[])
    start.add_argument("--capability", action="append", default=[])
    start.add_argument("--capability-evidence", action="append", default=[])
    start.add_argument("--skip", action="append", default=[])
    start.add_argument("--budget", action="append", default=[])
    start.add_argument("--stop-condition", action="append", default=[])
    start.add_argument("--outcome-kind", choices=tuple(sorted(control.OUTCOME_KINDS)))
    start.add_argument("--primary-outcome")
    start.add_argument("--proof-id")
    start.add_argument("--proof-description")
    start.add_argument("--document-authorization")
    start.add_argument("--contract-json")
    start.add_argument("--coverage-id", action="append", default=[])
    start.set_defaults(handler=control.command_start)
    escalate = commands.add_parser("escalate")
    add_repo_root(escalate)
    escalate.add_argument("--reason", action="append", required=True)
    escalate.add_argument("--capability", action="append", default=[])
    escalate.add_argument("--capability-evidence", action="append", default=[])
    escalate.add_argument("--skip", action="append", default=[])
    escalate.add_argument("--budget", action="append", default=[])
    escalate.set_defaults(handler=control.command_escalate)
    capabilities = commands.add_parser("capabilities")
    add_repo_root(capabilities)
    capabilities.add_argument("--enable", action="append", default=[])
    capabilities.add_argument("--capability-evidence", action="append", default=[])
    capabilities.add_argument("--skip", action="append", default=[])
    capabilities.add_argument("--budget", action="append", default=[])
    capabilities.set_defaults(handler=control.command_capabilities)
    event = commands.add_parser("event")
    add_repo_root(event)
    event.add_argument("--type", dest="event_type", required=True)
    event.add_argument("--summary", required=True)
    event.add_argument("--consume", action="append", default=[])
    event.add_argument("--evidence", action="append", default=[])
    event.add_argument("--node")
    event.add_argument("--action-id")
    event.add_argument("--phase", choices=("started", "result", "failed"))
    event.add_argument("--expected")
    event.add_argument("--owner", default="agent")
    event.set_defaults(handler=control.command_event)
    evidence = commands.add_parser("evidence")
    evidence_commands = evidence.add_subparsers(dest="evidence_command", required=True)
    evidence_link = evidence_commands.add_parser("link")
    add_repo_root(evidence_link)
    evidence_link.add_argument("--node", required=True)
    evidence_link.add_argument("--action-id", required=True)
    evidence_link.add_argument(
        "--classification",
        choices=tuple(sorted(control.ACTION_EVIDENCE_CLASSIFICATIONS)),
        required=True,
    )
    evidence_link.add_argument("--summary", required=True)
    evidence_link.add_argument("--evidence", action="append", default=[])
    evidence_link.add_argument("--plan-revision", type=int, required=True)
    evidence_link.add_argument("--state-revision", type=int, required=True)
    evidence_link.set_defaults(handler=control.command_evidence_link)
    plan = commands.add_parser("plan")
    add_repo_root(plan)
    plan.add_argument("--base-revision", type=int, required=True)
    plan.add_argument("--reason", required=True)
    plan.add_argument("--plan-file")
    plan.add_argument("--plan-json")
    plan.add_argument("--next-action")
    plan.add_argument("--durability", choices=tuple(sorted(control.CONTINUITY_DURABILITY_LEVELS)))
    plan.add_argument("--goal-change-confirmation")
    plan.add_argument("--numbering-change-confirmation")
    plan.set_defaults(handler=control.command_plan)
    milestone = commands.add_parser("milestone")
    milestone_commands = milestone.add_subparsers(dest="milestone_command", required=True)
    milestone_frontier = milestone_commands.add_parser("frontier")
    add_repo_root(milestone_frontier)
    milestone_frontier.set_defaults(handler=control.command_milestone_frontier)
    milestone_compile = milestone_commands.add_parser("compile")
    milestone_compile_commands = milestone_compile.add_subparsers(
        dest="milestone_compile_command", required=True
    )
    milestone_compile_inspect = milestone_compile_commands.add_parser("inspect")
    add_repo_root(milestone_compile_inspect)
    milestone_compile_inspect.add_argument("--milestone", required=True)
    milestone_compile_inspect.set_defaults(handler=control.command_milestone_compile_inspect)
    milestone_compile_apply = milestone_compile_commands.add_parser("apply")
    add_repo_root(milestone_compile_apply)
    milestone_compile_apply.add_argument("--milestone", required=True)
    milestone_compile_apply.add_argument("--plan-revision", type=int, required=True)
    milestone_compile_apply.add_argument("--state-revision", type=int, required=True)
    milestone_compile_apply.add_argument("--expected-facts-sha256", required=True)
    milestone_compile_apply.add_argument("--reason", required=True)
    milestone_compile_apply_input = milestone_compile_apply.add_mutually_exclusive_group(
        required=True
    )
    milestone_compile_apply_input.add_argument("--packet-file")
    milestone_compile_apply_input.add_argument("--packet-json")
    milestone_compile_apply.set_defaults(handler=control.command_milestone_compile_apply)
    milestone_execution = milestone_commands.add_parser("execution")
    milestone_execution_commands = milestone_execution.add_subparsers(
        dest="milestone_execution_command", required=True
    )
    milestone_execution_inspect = milestone_execution_commands.add_parser("inspect")
    add_repo_root(milestone_execution_inspect)
    milestone_execution_inspect.add_argument("--milestone", required=True)
    milestone_execution_inspect.set_defaults(handler=control.command_milestone_execution_inspect)
    milestone_execution_revalidate = milestone_execution_commands.add_parser("revalidate")
    add_repo_root(milestone_execution_revalidate)
    milestone_execution_revalidate.add_argument("--milestone", required=True)
    milestone_execution_revalidate.add_argument("--plan-revision", type=int, required=True)
    milestone_execution_revalidate.add_argument("--state-revision", type=int, required=True)
    milestone_execution_revalidate.set_defaults(handler=control.command_milestone_execution_revalidate)
    milestone_execution_select = milestone_execution_commands.add_parser("select")
    add_repo_root(milestone_execution_select)
    milestone_execution_select.add_argument("--milestone", required=True)
    milestone_execution_select.add_argument(
        "--mode", choices=tuple(sorted(control.EXECUTION_LANES)), required=True
    )
    milestone_execution_select.add_argument("--plan-revision", type=int, required=True)
    milestone_execution_select.add_argument("--state-revision", type=int, required=True)
    milestone_execution_select.add_argument("--confirmation-source", required=True)
    milestone_execution_select.add_argument(
        "--boundary", choices=tuple(sorted(control.EXECUTION_BOUNDARIES)),
        default="before_integration",
    )
    milestone_execution_select.add_argument("--worker-profile", default="light_worker")
    milestone_execution_select.add_argument("--worker-provider")
    milestone_execution_select.add_argument("--worker-model")
    milestone_execution_select.add_argument("--worker-reasoning")
    milestone_execution_select.set_defaults(handler=control.command_milestone_execution_select)
    milestone_handoff = milestone_commands.add_parser("handoff")
    milestone_handoff_commands = milestone_handoff.add_subparsers(
        dest="milestone_handoff_command", required=True
    )
    milestone_handoff_take = milestone_handoff_commands.add_parser("take")
    add_repo_root(milestone_handoff_take)
    milestone_handoff_take.add_argument("--milestone", required=True)
    milestone_handoff_take.add_argument("--plan-revision", type=int, required=True)
    milestone_handoff_take.add_argument("--state-revision", type=int, required=True)
    milestone_handoff_take.add_argument("--confirmation-source", required=True)
    milestone_handoff_take.set_defaults(handler=control.command_milestone_handoff_take)
    milestone_integration = milestone_commands.add_parser("integration")
    milestone_integration_commands = milestone_integration.add_subparsers(
        dest="milestone_integration_command", required=True
    )
    milestone_integration_inspect = milestone_integration_commands.add_parser("inspect")
    add_repo_root(milestone_integration_inspect)
    milestone_integration_inspect.add_argument("--milestone", required=True)
    milestone_integration_inspect.set_defaults(
        handler=control.command_milestone_integration_inspect
    )
    milestone_integration_record = milestone_integration_commands.add_parser("record")
    add_repo_root(milestone_integration_record)
    milestone_integration_record.add_argument("--milestone", required=True)
    milestone_integration_record.add_argument("--plan-revision", type=int, required=True)
    milestone_integration_record.add_argument("--state-revision", type=int, required=True)
    milestone_integration_record.add_argument(
        "--result", choices=("integrated", "conflicted", "blocked"), required=True
    )
    milestone_integration_record.add_argument("--summary", required=True)
    milestone_integration_record.add_argument("--evidence", action="append", required=True)
    milestone_integration_record.set_defaults(
        handler=control.command_milestone_integration_record
    )
    milestone_review = milestone_commands.add_parser("review")
    milestone_review_commands = milestone_review.add_subparsers(
        dest="milestone_review_command", required=True
    )
    milestone_review_inspect = milestone_review_commands.add_parser("inspect")
    add_repo_root(milestone_review_inspect)
    milestone_review_inspect.add_argument("--milestone", required=True)
    milestone_review_inspect.set_defaults(handler=control.command_milestone_review_inspect)
    milestone_review_record = milestone_review_commands.add_parser("record")
    add_repo_root(milestone_review_record)
    milestone_review_record.add_argument("--milestone", required=True)
    milestone_review_record.add_argument("--plan-revision", type=int, required=True)
    milestone_review_record.add_argument("--state-revision", type=int, required=True)
    milestone_review_record.add_argument(
        "--result", choices=tuple(sorted(control.MILESTONE_REVIEW_RESULTS)), required=True
    )
    milestone_review_record.add_argument("--packet")
    milestone_review_record.add_argument("--summary", required=True)
    milestone_review_record.add_argument("--evidence", action="append", required=True)
    milestone_review_record.set_defaults(handler=control.command_milestone_review_record)
    worker = milestone_commands.add_parser("worker")
    worker_commands = worker.add_subparsers(dest="worker_command", required=True)
    worker_prepare = worker_commands.add_parser("prepare")
    add_repo_root(worker_prepare)
    worker_prepare.add_argument("--packet", required=True)
    worker_prepare.add_argument("--worker-id")
    worker_prepare.set_defaults(handler=control.command_worker_prepare)
    worker_bind = worker_commands.add_parser("bind")
    add_repo_root(worker_bind)
    worker_bind.add_argument("--worker-id", required=True)
    worker_bind.add_argument("--executor-ref")
    worker_bind.add_argument("--provider")
    worker_bind.add_argument("--model")
    worker_bind.add_argument("--reasoning")
    worker_bind.add_argument("--blocked-reason")
    worker_bind.set_defaults(handler=control.command_worker_bind)
    worker_inspect = worker_commands.add_parser("inspect")
    add_repo_root(worker_inspect)
    worker_inspect.add_argument("--worker-id", required=True)
    worker_inspect.set_defaults(handler=control.command_worker_inspect)
    worker_capture = worker_commands.add_parser("capture")
    add_repo_root(worker_capture)
    worker_capture.add_argument("--worker-id", required=True)
    worker_capture.add_argument("--result-file")
    worker_capture.set_defaults(handler=control.command_worker_capture)
    worker_apply = worker_commands.add_parser("apply")
    add_repo_root(worker_apply)
    worker_apply.add_argument("--worker-id", required=True)
    worker_apply.set_defaults(handler=control.command_worker_apply)
    worker_finalize = worker_commands.add_parser("finalize")
    worker_finalize_commands = worker_finalize.add_subparsers(
        dest="worker_finalize_command", required=True
    )
    worker_finalize_inspect = worker_finalize_commands.add_parser("inspect")
    add_repo_root(worker_finalize_inspect)
    worker_finalize_inspect.add_argument("--worker-id", required=True)
    worker_finalize_inspect.set_defaults(handler=control.command_worker_finalize_inspect)
    worker_finalize_apply = worker_finalize_commands.add_parser("apply")
    add_repo_root(worker_finalize_apply)
    worker_finalize_apply.add_argument("--worker-id", required=True)
    worker_finalize_apply.add_argument("--plan-revision", type=int, required=True)
    worker_finalize_apply.add_argument("--state-revision", type=int, required=True)
    worker_finalize_apply.add_argument("--summary", required=True)
    worker_finalize_apply.add_argument("--evidence", action="append", required=True)
    worker_finalize_apply.set_defaults(handler=control.command_worker_finalize_apply)
    worker_cleanup = worker_commands.add_parser("cleanup")
    add_repo_root(worker_cleanup)
    worker_cleanup.add_argument("--worker-id", required=True)
    worker_cleanup.set_defaults(handler=control.command_worker_cleanup)
    checkpoint = commands.add_parser("checkpoint")
    add_repo_root(checkpoint)
    checkpoint.add_argument("--node")
    checkpoint.add_argument("--plan-revision", type=int, required=True)
    checkpoint.add_argument("--state-revision", type=int, required=True)
    checkpoint.add_argument("--status", choices=tuple(sorted(control.CONTINUITY_NODE_STATUSES)))
    checkpoint.add_argument("--summary", required=True)
    checkpoint.add_argument("--evidence", action="append", default=[])
    checkpoint.add_argument("--next-node")
    checkpoint.add_argument("--next-action")
    checkpoint.add_argument("--gap-id")
    checkpoint.add_argument("--gap-summary")
    checkpoint.add_argument(
        "--gap-owner", choices=tuple(sorted(control.CONTINUITY_GAP_OWNERS)), default="agent"
    )
    checkpoint.add_argument("--non-blocking", action="store_true")
    checkpoint.add_argument("--resolve-gap", action="append", default=[])
    checkpoint.set_defaults(handler=control.command_checkpoint)
    policy = commands.add_parser("policy")
    policy_commands = policy.add_subparsers(dest="policy_command", required=True)
    policy_inspect = policy_commands.add_parser("inspect")
    add_repo_root(policy_inspect)
    policy_inspect.add_argument("--path", action="append", required=True)
    policy_inspect.set_defaults(handler=control.command_policy)
    policy_set = policy_commands.add_parser("set")
    add_repo_root(policy_set)
    policy_set.add_argument("--policy-revision", type=int, required=True)
    policy_input = policy_set.add_mutually_exclusive_group(required=True)
    policy_input.add_argument("--policy-file")
    policy_input.add_argument("--policy-json")
    policy_set.add_argument("--confirmation-source", required=True)
    policy_set.add_argument("--reason", required=True)
    policy_set.set_defaults(handler=control.command_policy)
    policy_approve = policy_commands.add_parser("approve")
    add_repo_root(policy_approve)
    policy_approve.add_argument("--policy-revision", type=int, required=True)
    policy_approve.add_argument("--state-revision", type=int, required=True)
    policy_approve.add_argument("--node", required=True)
    policy_approve.add_argument("--path", action="append", required=True)
    policy_approve.add_argument("--confirmation-source", required=True)
    policy_approve.add_argument("--reason", required=True)
    policy_approve.set_defaults(handler=control.command_policy)
    impact = commands.add_parser("impact")
    impact_commands = impact.add_subparsers(dest="impact_command", required=True)
    impact_inspect = impact_commands.add_parser("inspect")
    add_repo_root(impact_inspect)
    impact_inspect.add_argument("--symbol", action="append", default=[])
    impact_inspect.add_argument("--file", action="append", default=[])
    impact_inspect.add_argument("--max-depth", type=int, default=8)
    impact_inspect.add_argument("--test-filter", action="append", default=[])
    impact_inspect.set_defaults(handler=control.command_impact)
    impact_record = impact_commands.add_parser("record")
    add_repo_root(impact_record)
    impact_record.add_argument("--node", required=True)
    impact_record.add_argument("--state-revision", type=int, required=True)
    impact_record.add_argument("--symbol", action="append", default=[])
    impact_record.add_argument("--file", action="append", default=[])
    impact_record.add_argument("--max-depth", type=int, default=8)
    impact_record.add_argument("--test-filter", action="append", default=[])
    impact_record.add_argument("--preserve", action="append", required=True)
    impact_record.add_argument("--verify", action="append", required=True)
    impact_record.add_argument("--risk", action="append", default=[])
    impact_record.add_argument("--uncertainty", action="append", default=[])
    impact_record.set_defaults(handler=control.command_impact)
    workspace = commands.add_parser("workspace")
    workspace_commands = workspace.add_subparsers(dest="workspace_command", required=True)
    workspace_checkpoint = workspace_commands.add_parser("checkpoint")
    workspace_checkpoint_commands = workspace_checkpoint.add_subparsers(
        dest="workspace_checkpoint_command", required=True
    )
    workspace_checkpoint_inspect = workspace_checkpoint_commands.add_parser("inspect")
    add_repo_root(workspace_checkpoint_inspect)
    workspace_checkpoint_inspect.add_argument(
        "--kind", choices=("baseline", "milestone", "archive")
    )
    workspace_checkpoint_inspect.add_argument("--scope", action="append", default=[])
    workspace_checkpoint_inspect.add_argument("--protection-id")
    workspace_checkpoint_inspect.set_defaults(handler=control.command_workspace_checkpoint)
    workspace_checkpoint_protect = workspace_checkpoint_commands.add_parser("protect")
    add_repo_root(workspace_checkpoint_protect)
    workspace_checkpoint_protect.add_argument("--node", required=True)
    workspace_checkpoint_protect.add_argument("--scope", action="append", default=[])
    workspace_checkpoint_protect.add_argument("--confirmation-source", required=True)
    workspace_checkpoint_protect.set_defaults(handler=control.command_workspace_checkpoint)
    workspace_checkpoint_create = workspace_checkpoint_commands.add_parser("create")
    add_repo_root(workspace_checkpoint_create)
    workspace_checkpoint_create.add_argument(
        "--kind", choices=("baseline", "milestone", "archive"), required=True
    )
    workspace_checkpoint_create.add_argument("--scope", action="append", default=[])
    workspace_checkpoint_create.add_argument("--protection-id")
    workspace_checkpoint_create.add_argument("--confirmation-source", required=True)
    workspace_checkpoint_create.set_defaults(handler=control.command_workspace_checkpoint)
    workspace_checkpoint_list = workspace_checkpoint_commands.add_parser("list")
    add_repo_root(workspace_checkpoint_list)
    workspace_checkpoint_list.set_defaults(handler=control.command_workspace_checkpoint)
    workspace_rollback = workspace_commands.add_parser("rollback")
    workspace_rollback_commands = workspace_rollback.add_subparsers(
        dest="workspace_rollback_command", required=True
    )
    workspace_rollback_inspect = workspace_rollback_commands.add_parser("inspect")
    add_repo_root(workspace_rollback_inspect)
    workspace_rollback_inspect.add_argument("--target", required=True)
    workspace_rollback_inspect.set_defaults(handler=control.command_workspace_rollback_inspect)
    proof = commands.add_parser("proof")
    add_repo_root(proof)
    proof.add_argument("--node", required=True)
    proof.add_argument("--proof-id", required=True)
    proof.add_argument("--plan-revision", type=int, required=True)
    proof.add_argument("--state-revision", type=int, required=True)
    proof.add_argument("--command", required=True)
    proof.add_argument("--revalidate", action="store_true")
    proof.add_argument("--evidence-file")
    proof.add_argument(
        "--failure-classification", choices=tuple(sorted(control.PROOF_FAILURE_CLASSIFICATIONS))
    )
    proof.set_defaults(handler=control.command_proof)
    debug = commands.add_parser("debug")
    debug_commands = debug.add_subparsers(dest="debug_command", required=True)
    debug_inspect = debug_commands.add_parser("inspect")
    add_repo_root(debug_inspect)
    debug_inspect.set_defaults(handler=control.command_debug_inspect)

    def add_debug_mutation(parser: argparse.ArgumentParser) -> None:
        add_repo_root(parser)
        parser.add_argument("--node", required=True)
        parser.add_argument("--state-revision", type=int, required=True)

    debug_begin = debug_commands.add_parser("begin")
    add_debug_mutation(debug_begin)
    debug_begin.add_argument("--symptom", required=True)
    debug_begin.add_argument("--scope", action="append", default=[])
    debug_begin.add_argument("--environment-ref", action="append", default=[])
    debug_begin.add_argument("--next-probe", required=True)
    debug_begin.set_defaults(handler=control.command_debug_begin)
    debug_case_search = debug_commands.add_parser("case-search")
    debug_case_search_commands = debug_case_search.add_subparsers(
        dest="debug_case_search_command", required=True
    )
    debug_case_search_bind = debug_case_search_commands.add_parser("bind")
    add_debug_mutation(debug_case_search_bind)
    debug_case_search_bind.add_argument(
        "--status",
        choices=tuple(sorted(control.DIAGNOSTIC_CASE_SEARCH_STATUSES - {"not_run"})),
        required=True,
    )
    debug_case_search_bind.add_argument("--memory-revision", type=int, required=True)
    debug_case_search_bind.add_argument("--memory-digest", required=True)
    debug_case_search_bind.add_argument("--query-digest", required=True)
    debug_case_search_bind.add_argument("--case-id", action="append", default=[])
    debug_case_search_bind.add_argument("--selected-case-id", action="append", default=[])
    debug_case_search_bind.add_argument("--warning", action="append", default=[])
    debug_case_search_bind.set_defaults(handler=control.command_debug_case_search_bind)
    debug_reproduction = debug_commands.add_parser("reproduction")
    debug_reproduction_commands = debug_reproduction.add_subparsers(
        dest="debug_reproduction_command", required=True
    )
    debug_reproduction_record = debug_reproduction_commands.add_parser("record")
    add_debug_mutation(debug_reproduction_record)
    debug_reproduction_record.add_argument(
        "--gate", choices=tuple(sorted(control.DIAGNOSTIC_REPRODUCTION_GATES)), required=True
    )
    debug_reproduction_record.add_argument("--proof-ref", action="append", default=[])
    debug_reproduction_record.add_argument("--evidence-ref", action="append", default=[])
    debug_reproduction_record.add_argument("--original-proof-ref", action="append", default=[])
    debug_reproduction_record.add_argument("--minimal-proof-ref", action="append", default=[])
    debug_reproduction_record.add_argument("--runs", type=int, required=True)
    debug_reproduction_record.add_argument("--failures", type=int, required=True)
    debug_reproduction_record.add_argument("--agent-runnable", choices=("yes", "no"), required=True)
    debug_reproduction_record.set_defaults(handler=control.command_debug_reproduction_record)
    debug_hypothesis = debug_commands.add_parser("hypothesis")
    debug_hypothesis_commands = debug_hypothesis.add_subparsers(
        dest="debug_hypothesis_command", required=True
    )
    debug_hypothesis_add = debug_hypothesis_commands.add_parser("add")
    add_debug_mutation(debug_hypothesis_add)
    debug_hypothesis_add.add_argument("--hypothesis-id", required=True)
    debug_hypothesis_add.add_argument("--statement", required=True)
    debug_hypothesis_add.add_argument("--prediction", required=True)
    debug_hypothesis_add.add_argument("--probe", required=True)
    debug_hypothesis_add.add_argument("--source-case-id")
    debug_hypothesis_add.set_defaults(handler=control.command_debug_hypothesis_add)
    debug_observe = debug_commands.add_parser("observe")
    add_debug_mutation(debug_observe)
    debug_observe.add_argument("--observation-id", required=True)
    debug_observe.add_argument("--hypothesis-id", required=True)
    debug_observe.add_argument("--expected", required=True)
    debug_observe.add_argument("--actual", required=True)
    debug_observe.add_argument(
        "--verdict", choices=tuple(sorted(control.DIAGNOSTIC_VERDICTS)), required=True
    )
    debug_observe.add_argument("--proof-ref", action="append", default=[])
    debug_observe.add_argument("--evidence-ref", action="append", default=[])
    debug_observe.set_defaults(handler=control.command_debug_observe)
    debug_resolve = debug_commands.add_parser("resolve")
    add_debug_mutation(debug_resolve)
    debug_resolve.add_argument(
        "--outcome", choices=tuple(sorted(control.DIAGNOSTIC_RESOLUTIONS)), required=True
    )
    debug_resolve.add_argument("--summary", required=True)
    debug_resolve.add_argument("--owner", choices=tuple(sorted(control.CONTINUITY_GAP_OWNERS)))
    debug_resolve.add_argument("--next-probe")
    debug_resolve.set_defaults(handler=control.command_debug_resolve)
    debug_recovery = debug_commands.add_parser("recovery")
    add_debug_mutation(debug_recovery)
    debug_recovery.add_argument(
        "--status", choices=tuple(sorted(control.DIAGNOSTIC_RECOVERY_STATUSES)), required=True
    )
    debug_recovery.add_argument("--proof-ref", action="append", default=[])
    debug_recovery.add_argument("--evidence-ref", action="append", default=[])
    debug_recovery.add_argument(
        "--probe-cleanup", choices=tuple(sorted(control.DIAGNOSTIC_PROBE_CLEANUP)), required=True
    )
    debug_recovery.add_argument("--risk", action="append", default=[])
    debug_recovery.add_argument(
        "--confirmation-owner", choices=tuple(sorted(control.CONTINUITY_GAP_OWNERS))
    )
    debug_recovery.set_defaults(handler=control.command_debug_recovery)
    memory = commands.add_parser("memory")
    memory_commands = memory.add_subparsers(dest="memory_command", required=True)
    memory_case = memory_commands.add_parser("case")
    memory_case_commands = memory_case.add_subparsers(dest="memory_case_command", required=True)
    memory_case_search = memory_case_commands.add_parser("search")
    add_repo_root(memory_case_search)
    memory_case_search.add_argument("--symptom", action="append", default=[])
    memory_case_search.add_argument("--keyword", action="append", default=[])
    memory_case_search.add_argument("--scope", action="append", default=[])
    memory_case_search.add_argument("--component", action="append", default=[])
    memory_case_search.add_argument("--environment", action="append", default=[])
    memory_case_search.add_argument("--observed-version")
    memory_case_search.add_argument("--limit", type=int, default=5)
    memory_case_search.set_defaults(handler=control.command_memory_case_search)
    memory_case_promote = memory_case_commands.add_parser("promote")
    add_repo_root(memory_case_promote)
    memory_case_promote.add_argument("--state-revision", type=int, required=True)
    memory_case_promote.add_argument("--memory-revision", type=int, required=True)
    memory_case_promote.add_argument("--case-id", required=True)
    memory_case_promote.add_argument("--title", required=True)
    memory_case_promote.add_argument("--keyword", action="append", required=True)
    memory_case_promote.add_argument("--symptom-signal", action="append", required=True)
    memory_case_promote.add_argument("--scope", action="append", default=[])
    memory_case_promote.add_argument("--component", action="append", default=[])
    memory_case_promote.add_argument("--environment", action="append", default=[])
    memory_case_promote.add_argument("--observed-version")
    memory_case_promote.add_argument("--cause-class", required=True)
    memory_case_promote.add_argument("--root-cause", required=True)
    memory_case_promote.add_argument("--distinguishing-signal", action="append", default=[])
    memory_case_promote.add_argument("--resolution", required=True)
    memory_case_promote.add_argument("--protective-test", action="append", default=[])
    memory_case_promote.add_argument("--lesson", required=True)
    memory_case_promote.add_argument("--evidence-ref", action="append", required=True)
    memory_case_promote.add_argument("--confirmation-source", required=True)
    memory_case_promote.set_defaults(handler=control.command_memory_case_promote)
    diagnostics = commands.add_parser("diagnostics")
    add_repo_root(diagnostics)
    diagnostics.add_argument("--id", dest="diagnostic_id", required=True)
    diagnostics.add_argument("--component", action="append", required=True)
    diagnostics.add_argument("--scope", action="append", required=True)
    diagnostics.add_argument("--layer", required=True)
    diagnostics.add_argument("--storage", required=True)
    diagnostics.add_argument("--retention", required=True)
    diagnostics.add_argument("--read", action="append", required=True)
    diagnostics.add_argument("--event", action="append", required=True)
    diagnostics.add_argument("--field", action="append", required=True)
    diagnostics.add_argument("--correlation", required=True)
    diagnostics.add_argument("--redaction", action="append", required=True)
    diagnostics.add_argument("--verify", action="append", required=True)
    diagnostics.add_argument("--limit", action="append", default=[])
    diagnostics.set_defaults(handler=control.command_diagnostics)
    finish = commands.add_parser("finish")
    add_repo_root(finish)
    finish.add_argument(
        "--status", choices=("passed", "failed", "blocked", "budget_exhausted"), required=True
    )
    finish.add_argument("--summary", required=True)
    finish.add_argument("--file", action="append", default=[])
    finish.add_argument("--validation", action="append", default=[])
    finish.add_argument("--risk", action="append", default=[])
    finish.add_argument("--confirmation-source")
    finish.set_defaults(handler=control.command_finish)
    abandon = commands.add_parser("abandon")
    add_repo_root(abandon)
    abandon.add_argument("--reason", required=True)
    abandon.set_defaults(handler=control.command_abandon)
    handoff = commands.add_parser("handoff")
    handoff_commands = handoff.add_subparsers(dest="handoff_command", required=True)
    handoff_export = handoff_commands.add_parser("export")
    add_repo_root(handoff_export)
    handoff_export.add_argument("--out", required=True)
    handoff_export.set_defaults(handler=control.command_handoff_export)
    handoff_import = handoff_commands.add_parser("import")
    add_repo_root(handoff_import)
    handoff_import.add_argument("--file", required=True)
    handoff_import.set_defaults(handler=control.command_handoff_import)
    recover = commands.add_parser("recover")
    add_repo_root(recover)
    recover.set_defaults(handler=control.command_recover)
    migrate = commands.add_parser("migrate")
    add_repo_root(migrate)
    migrate.set_defaults(handler=control.command_migrate)
    bootstrap = commands.add_parser("bootstrap")
    bootstrap_commands = bootstrap.add_subparsers(dest="bootstrap_command", required=True)
    bootstrap_inspect = bootstrap_commands.add_parser("inspect")
    add_repo_root(bootstrap_inspect)
    bootstrap_inspect.set_defaults(handler=control.command_bootstrap_inspect)
    bootstrap_apply = bootstrap_commands.add_parser("apply")
    add_repo_root(bootstrap_apply)
    bootstrap_apply.add_argument("--mode", choices=("fresh", "adopt", "replace"), required=True)
    bootstrap_apply.add_argument("--expected-task-id")
    bootstrap_apply.add_argument("--plan-file")
    bootstrap_apply.add_argument("--plan-json")
    bootstrap_apply.add_argument("--reason", default="bootstrap confirmed plan")
    bootstrap_apply.add_argument("--tier", choices=("direct", "team"), required=True)
    bootstrap_apply.add_argument("--requirement-receipt", required=True)
    bootstrap_apply.add_argument("--goal-confirmation-source", required=True)
    bootstrap_apply.add_argument("--plan-confirmation-source", required=True)
    bootstrap_apply.add_argument("--evidence", action="append", default=[])
    bootstrap_apply.add_argument("--scope", action="append", default=[])
    bootstrap_apply.add_argument(
        "--snapshot-mode",
        choices=("auto", "none", "manifest", "full"),
        default="auto",
        help="snapshot policy; Git defaults to a stat manifest, full copies are opt-in",
    )
    bootstrap_apply.add_argument(
        "--snapshot-scope",
        action="append",
        default=[],
        help="narrow the files preserved in the snapshot without changing the write gate",
    )
    bootstrap_apply.add_argument("--validation", action="append", default=[])
    bootstrap_apply.add_argument("--capability", action="append", default=[])
    bootstrap_apply.add_argument("--capability-evidence", action="append", default=[])
    bootstrap_apply.add_argument("--skip", action="append", default=[])
    bootstrap_apply.add_argument("--budget", action="append", default=[])
    bootstrap_apply.add_argument("--stop-condition", action="append", default=[])
    bootstrap_apply.add_argument(
        "--durability", choices=tuple(sorted(control.CONTINUITY_DURABILITY_LEVELS))
    )
    bootstrap_apply.set_defaults(handler=control.command_bootstrap_apply)
    refresh = commands.add_parser("refresh")
    add_repo_root(refresh)
    refresh.add_argument("--session-id")
    refresh.add_argument("--view", choices=("full", "agent-focus"), default="full")
    refresh.set_defaults(handler=control.command_refresh)
    resume = commands.add_parser("resume")
    add_repo_root(resume)
    resume.set_defaults(handler=control.command_resume, compact=True, strict=True)
    status = commands.add_parser("status")
    add_repo_root(status)
    status.add_argument("--compact", action="store_true")
    status.add_argument("--strict", action="store_true")
    status.add_argument("--view", choices=("full", "compact", "agent-focus"))
    status.add_argument("--session-key")
    status.add_argument("--project-context")
    status.set_defaults(handler=control.command_status)
    transition = commands.add_parser("transition")
    add_repo_root(transition)
    transition_input = transition.add_mutually_exclusive_group(required=True)
    transition_input.add_argument("--spec-file")
    transition_input.add_argument("--spec-json")
    transition.set_defaults(handler=control.command_transition)
    return parser
